name: build & publish Docker image
on:
  push:
    branches:
      - 5
jobs:
  lint-test:
    name: lint & test
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 16.x
    - run: npm install
    - run: npm run lint
    - run: npm test
  build-and-publish:
    name: build & publish Docker image
    needs: [lint-test]
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v2
      - name: log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - name: build Docker image & push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            derhuerst/db-rest:5
            derhuerst/db-rest:latest
